### ISSUE TITLE
大佬能不能发一下kcp-wechat-video的配置文件的写法

### ISSUE THREAD

**Issue by mayday12138** [Zzm317/V2Manager#2]
{
  "api": {
    "services": [
      "HandlerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "stats": {
  },
  "inbound": {
    "port": 26580,
    "protocol": "vmess",
    "settings": {
      "clients": []
    },
    "streamSettings": {
      "network": "kcp",
      "security": "auto",
	  "kcpSettings": {
                "header": {
                    "type": "wechat-video",
                }
    },
    "tag": "proxy"
  },
  "inboundDetour": [{
    "listen": "0.0.0.0",
    "port": 8301,
    "protocol": "dokodemo-door",
    "settings": {
      "address": "0.0.0.0"
    },
    "tag": "api"
  }],
  "log": {
    "loglevel": "debug",
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log"
  },
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "routing": {
    "settings": {
      "rules": [{
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      }]
    },
    "strategy": "rules"
  },
  "policy": {
    "levels": {
      "1": {
        "handshake": 4,
        "connIdle": 300,
        "uplinkOnly": 5,
        "downlinkOnly": 30,
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    }
  }
}

我这样写一直出错

**Comment by Zzm317** [comment]
对不起 v2ray的配置问题自己左转v2ray官方询问
